/**
 * @file correlationIdGenerator.js
 * @description Script Include for generating, parsing, and validating correlation
 *   IDs used throughout the DFW Automation Pipeline. Correlation IDs provide
 *   end-to-end traceability from ServiceNow RITM through vRO execution and
 *   back to the SNOW callback.
 *
 *   Format: RITM-{number}-{epoch}
 *     - RITM   : Fixed prefix identifying the source as a ServiceNow RITM
 *     - number : The RITM number (e.g., "0010001")
 *     - epoch  : Unix timestamp in milliseconds at generation time
 *
 *   Example: RITM-0010001-1679500000000
 *
 *   ServiceNow server-side globals used:
 *     - gs : GlideSystem utilities (for timestamp and logging)
 *
 * @module servicenow/integration/correlationIdGenerator
 */

/* global gs, Class, GlideDateTime */

'use strict';

/**
 * @class CorrelationIdGenerator
 * @classdesc Generates, parses, and validates correlation IDs in the
 *   RITM-{number}-{epoch} format. Designed as a ServiceNow Script Include
 *   that can be used by integration scripts, business rules, and workflows.
 */
const CorrelationIdGenerator = Class.create();

CorrelationIdGenerator.prototype = {

    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    /**
     * Fixed prefix for all correlation IDs generated by this module.
     * @constant {string}
     */
    PREFIX: 'RITM',

    /**
     * Separator character between correlation ID segments.
     * @constant {string}
     */
    SEPARATOR: '-',

    /**
     * Regular expression pattern for validating correlation ID format.
     * Matches: RITM-{digits}-{digits}
     * @constant {RegExp}
     */
    FORMAT_PATTERN: /^RITM-\d{4,10}-\d{13,}$/,

    /**
     * Minimum valid epoch timestamp (2020-01-01T00:00:00.000Z).
     * Used to reject obviously invalid timestamps.
     * @constant {number}
     */
    MIN_EPOCH: 1577836800000,

    /**
     * Maximum reasonable epoch timestamp (2050-01-01T00:00:00.000Z).
     * Used to reject obviously invalid timestamps.
     * @constant {number}
     */
    MAX_EPOCH: 2524608000000,

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /**
     * Creates a new CorrelationIdGenerator instance.
     *
     * @constructor
     */
    initialize: function () {
        // No initialization required; stateless utility
    },

    // -----------------------------------------------------------------------
    // Public API — generate
    // -----------------------------------------------------------------------

    /**
     * Generates a new correlation ID for the given RITM number.
     *
     * The correlation ID is constructed as:
     *   RITM-{ritmNumber}-{currentEpochMillis}
     *
     * The epoch timestamp ensures uniqueness even if the same RITM generates
     * multiple correlation IDs (e.g., retry scenarios).
     *
     * @param {string} ritmNumber - The RITM number (e.g., "0010001", "RITM0010001").
     *   If the number includes the "RITM" prefix, it is automatically stripped.
     * @returns {string} The generated correlation ID.
     * @throws {Error} If ritmNumber is empty, null, or not a valid number after
     *   prefix stripping.
     *
     * @example
     * var generator = new CorrelationIdGenerator();
     * var id = generator.generate('0010001');
     * // => "RITM-0010001-1679500000000"
     *
     * @example
     * var id = generator.generate('RITM0010001');
     * // => "RITM-0010001-1679500000000" (prefix auto-stripped)
     */
    generate: function (ritmNumber) {
        if (!ritmNumber || ritmNumber.toString().trim() === '') {
            throw new Error(
                '[DFW-6001] CorrelationIdGenerator.generate: ritmNumber is required'
            );
        }

        const normalizedNumber = this._normalizeRitmNumber(ritmNumber);

        if (!this._isValidRitmNumber(normalizedNumber)) {
            throw new Error(
                '[DFW-6002] CorrelationIdGenerator.generate: invalid RITM number "' +
                ritmNumber + '". Expected numeric string (e.g., "0010001").'
            );
        }

        const epoch = this._getCurrentEpoch();

        const correlationId = this.PREFIX +
            this.SEPARATOR + normalizedNumber +
            this.SEPARATOR + epoch;

        gs.debug('CorrelationIdGenerator: Generated correlation ID: ' + correlationId);

        return correlationId;
    },

    // -----------------------------------------------------------------------
    // Public API — parse
    // -----------------------------------------------------------------------

    /**
     * Parses a correlation ID string into its component parts.
     *
     * @param {string} correlationId - The correlation ID to parse.
     * @returns {{prefix: string, ritmNumber: string, timestamp: number, generatedAt: string}|null}
     *   Parsed components, or null if the format is invalid.
     *   - prefix      : Always "RITM".
     *   - ritmNumber  : The RITM number portion (e.g., "0010001").
     *   - timestamp   : The epoch timestamp as a number.
     *   - generatedAt : ISO 8601 string representation of the timestamp.
     *
     * @example
     * var generator = new CorrelationIdGenerator();
     * var parsed = generator.parse('RITM-0010001-1679500000000');
     * // => {
     * //   prefix: 'RITM',
     * //   ritmNumber: '0010001',
     * //   timestamp: 1679500000000,
     * //   generatedAt: '2023-03-22T16:26:40.000Z'
     * // }
     *
     * @example
     * var invalid = generator.parse('INVALID-FORMAT');
     * // => null
     */
    parse: function (correlationId) {
        if (!correlationId || typeof correlationId !== 'string') {
            return null;
        }

        const trimmed = correlationId.trim();

        // Split on separator; expect exactly 3 parts
        const parts = trimmed.split(this.SEPARATOR);
        if (parts.length !== 3) {
            gs.debug('CorrelationIdGenerator.parse: Expected 3 parts, got ' + parts.length);
            return null;
        }

        const prefix = parts[0];
        const ritmNumber = parts[1];
        const epochStr = parts[2];

        // Validate prefix
        if (prefix !== this.PREFIX) {
            gs.debug('CorrelationIdGenerator.parse: Invalid prefix "' + prefix + '"');
            return null;
        }

        // Validate RITM number is numeric
        if (!this._isValidRitmNumber(ritmNumber)) {
            gs.debug('CorrelationIdGenerator.parse: Invalid RITM number "' + ritmNumber + '"');
            return null;
        }

        // Validate epoch is a valid number
        const epoch = parseInt(epochStr, 10);
        if (isNaN(epoch) || epoch.toString() !== epochStr) {
            gs.debug('CorrelationIdGenerator.parse: Invalid epoch "' + epochStr + '"');
            return null;
        }

        return {
            prefix: prefix,
            ritmNumber: ritmNumber,
            timestamp: epoch,
            generatedAt: new Date(epoch).toISOString()
        };
    },

    // -----------------------------------------------------------------------
    // Public API — validate
    // -----------------------------------------------------------------------

    /**
     * Validates that a string is a properly formatted correlation ID.
     *
     * Checks:
     *   1. Non-null/empty string
     *   2. Matches the RITM-{number}-{epoch} format regex
     *   3. RITM number is numeric and between 4-10 digits
     *   4. Epoch timestamp is within a reasonable range (2020-2050)
     *   5. String can be successfully parsed
     *
     * @param {string} correlationId - The correlation ID to validate.
     * @returns {{valid: boolean, reason: string}} Validation result.
     *   - valid  : True if the correlation ID is valid.
     *   - reason : Human-readable reason if invalid; empty string if valid.
     *
     * @example
     * var generator = new CorrelationIdGenerator();
     *
     * var r1 = generator.validate('RITM-0010001-1679500000000');
     * // => { valid: true, reason: '' }
     *
     * var r2 = generator.validate('INVALID');
     * // => { valid: false, reason: 'Does not match expected format RITM-{number}-{epoch}' }
     *
     * var r3 = generator.validate('RITM-0010001-9999');
     * // => { valid: false, reason: 'Epoch timestamp is outside valid range' }
     */
    validate: function (correlationId) {
        // Check 1: Non-null/empty
        if (!correlationId || typeof correlationId !== 'string' ||
            correlationId.trim() === '') {
            return {
                valid: false,
                reason: 'Correlation ID is null, empty, or not a string'
            };
        }

        const trimmed = correlationId.trim();

        // Check 2: Regex format match
        if (!this.FORMAT_PATTERN.test(trimmed)) {
            return {
                valid: false,
                reason: 'Does not match expected format RITM-{number}-{epoch}'
            };
        }

        // Check 3 & 4: Parse and validate components
        const parsed = this.parse(trimmed);
        if (!parsed) {
            return {
                valid: false,
                reason: 'Failed to parse correlation ID components'
            };
        }

        // Check 4: Epoch range
        if (parsed.timestamp < this.MIN_EPOCH || parsed.timestamp > this.MAX_EPOCH) {
            return {
                valid: false,
                reason: 'Epoch timestamp is outside valid range (' +
                    this.MIN_EPOCH + ' to ' + this.MAX_EPOCH + ')'
            };
        }

        return {
            valid: true,
            reason: ''
        };
    },

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    /**
     * Normalizes a RITM number by stripping the "RITM" prefix if present
     * and trimming whitespace.
     *
     * @private
     * @param {string} ritmNumber - Raw RITM number input.
     * @returns {string} Normalized numeric-only RITM number.
     */
    _normalizeRitmNumber: function (ritmNumber) {
        let str = ritmNumber.toString().trim();

        // Strip "RITM" prefix (case-insensitive)
        if (str.toUpperCase().indexOf('RITM') === 0) {
            str = str.substring(4);
        }

        return str.trim();
    },

    /**
     * Checks if a string is a valid RITM number (4-10 digits, all numeric).
     *
     * @private
     * @param {string} number - The RITM number to validate.
     * @returns {boolean} True if valid.
     */
    _isValidRitmNumber: function (number) {
        if (!number || number === '') {
            return false;
        }
        return /^\d{4,10}$/.test(number);
    },

    /**
     * Returns the current epoch timestamp in milliseconds.
     * Uses GlideDateTime if available (ServiceNow server), otherwise falls
     * back to Date.now().
     *
     * @private
     * @returns {string} Current epoch timestamp as a string.
     */
    _getCurrentEpoch: function () {
        try {
            const gdt = new GlideDateTime();
            return gdt.getNumericValue().toString();
        } catch (e) {
            // Fallback for non-ServiceNow environments (testing)
            return Date.now().toString();
        }
    },

    /**
     * Type identifier for ServiceNow Script Include framework.
     * @type {string}
     */
    type: 'CorrelationIdGenerator'
};
